version: '3.2'

networks:
  dev:
    driver: bridge 
# ${REGISTRY:-service-one}/customer-service.api:${PLATFORM:-linux}-${TAG:-latest}
services:
  ids-service:
    image: bilalsahli/test:latest
    depends_on:
      - "ids_db"
    container_name: testcontainer
    ports:
      - "9184:9184"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ConnectionString=Server=postgres-container;Username=postgres;Password=1234;Port=5452;Database=mydatabase;
    networks:
      - dev

  ids_db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - PGPASSWORD=1234
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydatabase
    expose:
      - "5452" # Publishes 5452 to other containers but NOT to host machine
    ports:
      - "5452:5452"
    restart: always

    networks:
      - dev
    command: -p 5452

